# Generated by Django 5.2.7 on 2025-10-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'entry Password',
                'verbose_name_plural': 'entry Passwords',
                'db_table': 'entry_password',
            },
        ),
    ]
