# Generated by Django 5.2.7 on 2025-10-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marker_photos/'),
        ),
    ]
