# Generated by Django 5.2.7 on 2025-10-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_entrypassword'),
        ('users', '0004_marker_image'),
    ]

    operations = [
    ]
