# Generated by Django 5.2.7 on 2025-10-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_votetype_customuser_is_inquisitor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Banned IP Address')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blacklisted IP',
                'verbose_name_plural': 'Blacklisted IPs',
                'db_table': 'blacklisted_ips',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_known_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Known IP'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='outcome',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired (No Nomination)')], default='PENDING', max_length=20),
        ),
    ]
