# Generated by Django 5.2.7 on 2025-10-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_vote_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='outcome',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired (No Nomination)')], default='PENDING', max_length=20),
        ),
    ]
