# Generated by Django 5.2.7 on 2025-11-01 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_blacklistedip_customuser_last_known_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the user was assigned their current role'),
        ),
        migrations.AlterField(
            model_name='votetype',
            name='pass_condition',
            field=models.CharField(choices=[('MAJORITY', 'Majority'), ('UNANIMOUS_TARGET', 'Unanimous Target Role'), ('UNANIMOUS_ALL_VOTED', 'Unanimous Voted'), ('UNANIMOUS_AGREE', 'Unanimous Agree (No Disagree)')], help_text='Is voting successful', max_length=50),
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
